
png("Plot4.png", width=480, height=480)
plot(Plot2$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="Day", axes=F,col="black", ylim=c(0,40)) 
par(new=T)
plot(Plot2$Sub_metering_2, type="l", ylab="Energy sub metering", xlab="Day", axes=F,col="red") 
par(new=T)
plot(Plot2$Sub_metering_3, type="l", ylab="Energy sub metering", xlab="Day", axes=F,col="blue")
axis(side=2, at=c(0,10,20,30), labels=c("0","10","20","30"))
axis(side=1, at=c(1,1440,2880), labels=c("Thu","Fry","Sat"))
box()
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub metering 1","Sub metering 2","Sub metering 3"),bg="white")
dev.off() 